name: Build Android APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Java
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "000000000000",
              "project_id": "dfirst-mobile",
              "storage_bucket": "dfirst-mobile.appspot.com"
            },
            "client": [{
              "client_info": {
                "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                "android_client_info": {
                  "package_name": "com.anonymous.DFirst"
                }
              },
              "api_key": [{
                "current_key": "dummy_key"
              }]
            }]
          }' > google-services.json

      - name: Build Android
        run: |
          npm install --legacy-peer-deps
          npx expo prebuild --platform android --clean
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk 